protocol bgp bgpexchange_hk_v4 {
    local 100.66.61.83 as LOCAL_AS;
    neighbor 100.66.63.254 as 24381;
    graceful restart on;

    ipv4 {
        import all;
        import limit 2000000 action restart;
        export none;
    };
}

protocol bgp bgpexchange_hk_v6 from upstream_v6 {
    neighbor 2a0e:8f01:1000:16::1 as 24381;
    source address 2a0e:8f01:1000:16::157;

    ipv6 {
        import all;
        import limit 500000 action restart;
    };
}
