protocol bgp bgptunnel_no_v6 from upstream_v6 {
    neighbor 2a0c:9a40:a004::1d as 209533;
    source address 2a0c:9a40:a004::1e;

    ipv6 {
        import filter {
            if !valid_public_v6() then reject;
            bgp_local_pref = 180;
            accept;
        };
        import limit 500000 action restart;
    };
}
