protocol bgp hyehost_nz from upstream_v6 {
    neighbor fd00:200:64:1::5 as 47272;
    source address fd00:200:64::5;
    multihop 2;

    hold time 90;
    keepalive time 30;

    ipv6 {
        import filter {
            bgp_local_pref = 220;
            accept;
        };
        import limit 500000 action restart;
    };
}
