protocol bgp hyehost_uk from upstream_v6 {
    neighbor fd00:200:21:1::17 as 47272;
    source address fd00:200:21::17;
    multihop 2;

    hold time 90;
    keepalive time 30;

    ipv6 {
        import all;
        import limit 500000 action restart;
    };
}
