protocol bgp lunalight_v6 from upstream_v6 {
    neighbor fd00:218:822:2014:23::1 as 201423;
    source address fd00:218:822:2014:23::;

    ipv6 {
        import all;
        import limit 500000 action restart;
    };
}
