[Interface]
Address = 10.249.20.74/30, 2a0c:9a40:a008::4a/126
PrivateKey = ${WG_BGPTUNNEL_ES_PRIVATE_KEY}
Table = off

[Peer]
PublicKey = W0pI832mL5u7JzJjiE68dyS95mIGBDqGgSxSZromEGY=
Endpoint = 45.134.91.18:51825
AllowedIPs = 10.249.20.73/30, ::/0
PersistentKeepalive = 60
