[Interface]
Address = 10.249.16.30/30, 2a0c:9a40:a004::1e/126
PrivateKey = ${WG_BGPTUNNEL_NO_PRIVATE_KEY}
Table = off

[Peer]
PublicKey = W0pI832mL5u7JzJjiE68dyS95mIGBDqGgSxSZromEGY=
Endpoint = 45.134.89.18:51831
AllowedIPs = 10.249.16.29/30, 2a0c:9a40:a004::1d/126
PersistentKeepalive = 60
