[Interface]
Address = fd00:218:822:100::/127
PrivateKey = ${WG_CORE_PRIVATE_KEY}
Table = off
MTU = 1420

[Peer]
PublicKey = bzrmTDbQNHyonbc1jnouNvQqqNEjLKKzlowODgqLa0I=
Endpoint = gre-gateway.as218822.svc.cluster.local:51821
AllowedIPs = ::/0
PersistentKeepalive = 25
