[Interface]
Address = fd00:218:822:100::/127
PrivateKey = ${WG_CORE_PRIVATE_KEY}
Table = off

[Peer]
PublicKey = bzrmTDbQNHyonbc1jnouNvQqqNEjLKKzlowODgqLa0I=
Endpoint = 10.0.0.10:51821
AllowedIPs = ::/0
PersistentKeepalive = 25
