[Interface]
Address = fd00:200:120::8/128
PrivateKey = ${WG_UPSTREAM_PRIVATE_KEY}

[Peer]
PublicKey = Szg6v+KLp2dJvS1UoD90xXgnwBeWMIKhMtZgdZTY7kY=
Endpoint = 23.172.120.2:51930
AllowedIPs = fd00:200:120:1::8/128
PersistentKeepalive = 25
