[Interface]
Address = fd00:200:64::5/128
PrivateKey = ${WG_UPSTREAM_PRIVATE_KEY}
Table = off

[Peer]
PublicKey = f7EykLzH97LXW1Vs+L7/aW7M5he+2x5BPB9PaLsEOyo=
Endpoint = 103.208.85.221:51823
AllowedIPs = ::/0
PersistentKeepalive = 25
