[Interface]
Address = fd00:200:21::17/128
PrivateKey = ${WG_UPSTREAM_PRIVATE_KEY}
Table = off
MTU = 1420

[Peer]
PublicKey = ny/TaW8Tn/T+tW1cf11gNTTvvnlJrq3FQdmeJnZcnj0=
Endpoint = 199.47.240.243:51839
AllowedIPs = ::/0
PersistentKeepalive = 25
