[Interface]
Address = fd00:200:21::17/128
PrivateKey = ${WG_UPSTREAM_PRIVATE_KEY}

[Peer]
PublicKey = ny/TaW8Tn/T+tW1cf11gNTTvvnlJrq3FQdmeJnZcnj0=
Endpoint = 199.47.240.243:51839
AllowedIPs = fd00:200:21:1::17/128
PersistentKeepalive = 25
