[Interface]
Address = fd00:218:822:735::/127
PrivateKey = ${WG_LAGRANGE_CORE_PRIVATE_KEY}
Table = off

[Peer]
PublicKey = NhPhS5zd172eHHcElAGfJ9Iel50XpDHTEfjq9IV2f3Q=
Endpoint = 103.146.103.64:51820
AllowedIPs = ::/0
PersistentKeepalive = 25
