[Interface]
Address = 100.65.16.110/30, 2a11:6c7:f08:1b::2/64
PrivateKey = ${WG_ROUTE64_SG_PRIVATE_KEY}
Table = off
MTU = 1420

[Peer]
PublicKey = rs2xR/cYjfLaaUU/gRYKlpc6A3phiqaryr6pfqmJ+WQ=
Endpoint = 169.128.221.9:20050
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 15
