[Interface]
Address = 100.65.16.110/30, 2a11:6c7:f08:1b::2/64
PrivateKey = ${WG_ROUTE64_SG_PRIVATE_KEY}
Table = off

[Peer]
PublicKey = pWJXUGoeqj9P3v/e29JTPDvAVBXIk5PCjmyWM1xEI0w=
Endpoint = [2a11:6c7:27::1]:20050
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 15
