[Interface]
Address = fd00:218:822:473::/127
PrivateKey = ${WG_VULTR_CORE_PRIVATE_KEY}
Table = off

[Peer]
PublicKey = fWI22ZIpvRfz4QM99/p2gHIu+re8N6agrb0isbZM8Qg=
Endpoint = 158.247.230.77:51820
AllowedIPs = ::/0
PersistentKeepalive = 25
