[Interface]
Address = fd00:218:822:473::1/127
ListenPort = 51820
PrivateKey = ${WG_VULTR_EDGE_PRIVATE_KEY}
Table = off

[Peer]
PublicKey = 2vnwktCtudjDjCKzy5svVk929/8cSz5GEGZsGF758x0=
AllowedIPs = ::/0
