services:
  bird:
    build:
      context: .
    container_name: as218822-bird
    network_mode: host
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
      - NET_RAW
    security_opt:
      - no-new-privileges:true
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file:
      - ./bird/.env.keys
    tmpfs:
      - /run/bird:mode=0755,size=1m
      - /var/lib/zerotier-one:mode=0700,size=16m
    volumes:
      - ./bird/.env:/etc/bird/.env:ro
      - ./bird/bird.conf:/etc/bird/bird.conf:ro
      - ./bird/local.conf:/etc/bird/local.conf:ro
      - ./bird/peers:/etc/bird/peers:ro
      - ./tunnels:/etc/tunnels:ro
