[Interface]
Address = fd00:218:822:735::1/127
ListenPort = 51820
PrivateKey = ${WG_LAGRANGE_EDGE_PRIVATE_KEY}
Table = off

[Peer]
PublicKey = zMTAsLGv1MsS+BYYxordISNsdlN23iyr85iGJjs9dyE=
AllowedIPs = ::/0
