log stderr all;

include "/etc/bird/local.conf";

define LOCAL_AS = 218822;
define OWN_PREFIX = 2a06:9801:ff0::/44;
define LUNALIGHT_PREFIXES = [
    2a0f:6284:b::/48,
    2a0f:6284:c::/48
];

protocol device {
    scan time 10;
}

protocol direct direct_v6 {
    ipv6;
}

filter import_core_v6 {
    if net = OWN_PREFIX then accept;
    reject;
}

filter import_lunalight_v6 {
    if net ~ LUNALIGHT_PREFIXES then {
        bgp_local_pref = 220;
        accept;
    }
    reject;
}

filter export_core_v6 {
    if source = RTS_BGP && net != OWN_PREFIX then accept;
    reject;
}

filter export_upstream_v6 {
    if net = OWN_PREFIX && source = RTS_BGP then accept;
    reject;
}

filter export_kernel_v6 {
    if source = RTS_BGP then accept;
    reject;
}

protocol kernel kernel_v6 {
    ipv6 {
        import none;
        export filter export_kernel_v6;
    };
    merge paths on limit 16;
}

template bgp upstream_v6 {
    local as LOCAL_AS;
    graceful restart on;

    ipv6 {
        import none;
        export filter export_upstream_v6;
    };
}

include "/run/bird/peers/*.conf";
