[Interface]
Address = fd00:218:822:100::1/127
ListenPort = 51821
PrivateKey = ${WG_GRE_GATEWAY_PRIVATE_KEY}
Table = off

[Peer]
PublicKey = guHhnQ4SzmkIn+RYBa+WW/sH1hggf6EcX5JX/rPTT2c=
AllowedIPs = ::/0
