protocol bgp lagrange_v6 {
    local 2a0f:85c2:101::35 as LOCAL_AS;
    neighbor 2a0f:85c2:101::ff as UPSTREAM_AS;
    graceful restart on;

    ipv6 {
        import none;
        export filter export_own_v6;
    };
}
